### ISSUE TITLE
OSError: sndfile library not found，How to solve this problem？

### ISSUE THREAD

**Issue by leyangxing** [f90/Wave-U-Net-Pytorch#11]
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from data.dataset import SeparationDataset
  File "/root/autodl-tmp/wave-u-net/data/dataset.py", line 9, in <module>
    from data.utils import load
  File "/root/autodl-tmp/wave-u-net/data/utils.py", line 3, in <module>
    import soundfile
  File "/root/miniconda3/lib/python3.8/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

When I start training, I will report this error

**Comment by f90** [comment]
Hey, this sounds like you don't have libsndfile installed. You need to install that library first on your machine before you can run the code!

**Comment by leyangxing** [comment]
Thank you！resolved
